version: 2

group_defaults:
  always_pending:
    labels:
      - do-not-merge
      - needs-rebase
      - work-in-progress
  approve_by_comment:
    enabled: true
    approve_regex: '^:\+1:'

groups:
  reviewers:
    required: 1
    teams:
      - workbench-dev
      - belatrix-fc
  tech-lead:
    required: -1
    users:
      - pshapiro4broad
      - ahaessly
