language: node_js
dist: trusty
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - "8"
script:
  # run build script specified in package.json
  - npm run ci
  # call script for deploying of produced artifacts
  #- bash ./.travis-deploy.sh


