language: node_js
dist: trusty
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
node_js:
  - "8"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  # run build script specified in package.json
  - npm run ci
  # call script for deploying of produced artifacts
  #- bash ./.travis-deploy.sh


