language: node_js
dist: trusty
addons:
  apt:
    packages:
    - xvfb
chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
node_js:
  - "8"
script:
  # run build script specified in package.json
  - npm run ci
  # call script for deploying of produced artifacts
  #- bash ./.travis-deploy.sh


